#!/usr/bin/env python3
"""Render the Homebrew formula for forgeo from release binary assets.

Used by the release pipeline (see .github/workflows/ci.yml, publish-homebrew)
to keep the ``lucaGazzola/homebrew-forgeo`` tap in sync with the binaries
published on every GitHub Release:

    python scripts/render_homebrew_formula.py v0.4.0 binaries > forgeo.rb

Prints the Ruby formula to stdout. ``binaries`` must hold the release assets
named ``forgeo-<os>-<arch>``. The formula mirrors the install.sh one-liner:
a standalone prebuilt binary per platform, no Python needed.
"""

from __future__ import annotations

import hashlib
import pathlib
import sys

SOURCE_REPO = "lucaGazzola/forgeo"
HOMEPAGE = "https://forgeo.org"
DESCRIPTION = (
    "A scheduled software forgeo: executes backlog tasks on main, refactors when idle, "
    "and writes BLOCKER.md when it needs human input."
)

#: Published binaries per Homebrew platform block. ``None`` condition means
#: the ``else`` branch of the surrounding ``if`` (the platform default).
TARGETS: dict[str, list[tuple[str | None, str]]] = {
    "macos": [
        ("Hardware::CPU.arm?", "forgeo-darwin-arm64"),
        (None, "forgeo-darwin-amd64"),
    ],
    "linux": [
        ("Hardware::CPU.intel?", "forgeo-linux-amd64"),
    ],
}


def sha256(path: pathlib.Path) -> str:
    """Hex sha256 of a (potentially large) binary, read in chunks."""
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(65536), b""):
            digest.update(chunk)
    return digest.hexdigest()


def render(version: str, assets_dir: pathlib.Path) -> str:
    """Render the complete formula for ``version`` using ``assets_dir``."""
    lines = [
        "# Homebrew formula for forgeo.",
        "#",
        "# This file is generated by the release pipeline in the forgeo repository",
        "# (.github/workflows/ci.yml, publish-homebrew job): every new tag vX.Y.Z",
        "# downloads the prebuilt binaries, computes their sha256 and updates this",
        "# formula. Do not edit by hand; re-run the pipeline instead.",
        "",
        "class Forgeo < Formula",
        f'  desc "{DESCRIPTION}"',
        f'  homepage "{HOMEPAGE}"',
        f"  version \"{version}\"",
        '  license "MIT"',
        "",
    ]
    default_asset = TARGETS["linux"][0][1]
    lines.append(
        f'  url "https://github.com/{SOURCE_REPO}/releases/download/v{version}/{default_asset}"'
    )
    lines.append("")
    for platform, targets in TARGETS.items():
        lines.append(f"  on_{platform} do")
        for condition, asset in targets:
            url = f"https://github.com/{SOURCE_REPO}/releases/download/v{version}/{asset}"
            digest = sha256(assets_dir / asset)
            if condition is None:
                lines.append("    else")
            else:
                lines.append(f"    if {condition}")
            lines.append(f'      url "{url}"')
            lines.append(f'      sha256 "{digest}"')
        lines.append("    end")
        lines.append("  end")
        lines.append("")
    lines.extend(
        [
            "  def install",
            '    binary = Pathname.glob("forgeo-*").first',
            '    bin.install binary => "forgeo"',
            "  end",
            "",
            "  test do",
            '    assert_match "forgeo #{version}", shell_output("#{bin}/forgeo --version")',
            "  end",
            "end",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} VERSION ASSETS_DIR", file=sys.stderr)
        return 2
    version = sys.argv[1].removeprefix("v")
    assets_dir = pathlib.Path(sys.argv[2])
    missing = [asset for targets in TARGETS.values() for _, asset in targets
               if not (assets_dir / asset).is_file()]
    if missing:
        print(f"error: missing binary assets in {assets_dir}: {', '.join(missing)}", file=sys.stderr)
        return 1
    print(render(version, assets_dir), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
